exclude:
- README.md
- dev_note/vst3_dev.md
- index.md
- manual/AccumulativeRingMod/AccumulativeRingMod_en.md
- manual/AccumulativeRingMod/AccumulativeRingMod_ja.md
- manual/BasicLimiter/BasicLimiter_en.md
- manual/BasicLimiter/BasicLimiter_ja.md
- manual/ClangSynth/ClangSynth_en.md
- manual/ClangSynth/ClangSynth_ja.md
- manual/CollidingCombSynth/CollidingCombSynth_en.md
- manual/CollidingCombSynth/CollidingCombSynth_ja.md
- manual/CombDistortion/CombDistortion_en.md
- manual/CombDistortion/CombDistortion_ja.md
- manual/CubicPadSynth/CubicPadSynth_en.md
- manual/CubicPadSynth/CubicPadSynth_ja.md
- manual/EnvelopedSine/EnvelopedSine_en.md
- manual/EnvelopedSine/EnvelopedSine_ja.md
- manual/EsPhaser/EsPhaser_en.md
- manual/EsPhaser/EsPhaser_ja.md
- manual/FDN64Reverb/FDN64Reverb_en.md
- manual/FDN64Reverb/FDN64Reverb_ja.md
- manual/FDNCymbal/FDNCymbal_en.md
- manual/FDNCymbal/FDNCymbal_ja.md
- manual/FeedbackPhaser/FeedbackPhaser_en.md
- manual/FeedbackPhaser/FeedbackPhaser_ja.md
- manual/IterativeSinCluster/IterativeSinCluster_en.md
- manual/IterativeSinCluster/IterativeSinCluster_ja.md
- manual/L4Reverb/L4Reverb_en.md
- manual/L4Reverb/L4Reverb_ja.md
- manual/LatticeReverb/LatticeReverb_en.md
- manual/LatticeReverb/LatticeReverb_ja.md
- manual/LightPadSynth/LightPadSynth_en.md
- manual/LightPadSynth/LightPadSynth_ja.md
- manual/LongPhaser/LongPhaser_en.md
- manual/LongPhaser/LongPhaser_ja.md
- manual/MaybeSnare/MaybeSnare_en.md
- manual/MaybeSnare/MaybeSnare_ja.md
- manual/MembraneSynth/MembraneSynth_en.md
- manual/MembraneSynth/MembraneSynth_ja.md
- manual/MiniCliffEQ/MiniCliffEQ_en.md
- manual/MiniCliffEQ/MiniCliffEQ_ja.md
- manual/NarrowingDelay/NarrowingDelay_en.md
- manual/NarrowingDelay/NarrowingDelay_ja.md
- manual/OrdinaryPhaser/OrdinaryPhaser_en.md
- manual/OrdinaryPhaser/OrdinaryPhaser_ja.md
- manual/ParallelComb/ParallelComb_en.md
- manual/ParallelComb/ParallelComb_ja.md
- manual/ParallelDetune/ParallelDetune_en.md
- manual/ParallelDetune/ParallelDetune_ja.md
- manual/PitchShiftDelay/PitchShiftDelay_en.md
- manual/PitchShiftDelay/PitchShiftDelay_ja.md
- manual/RingModSpacer/RingModSpacer_en.md
- manual/RingModSpacer/RingModSpacer_ja.md
- manual/SevenDelay/SevenDelay_en.md
- manual/SevenDelay/SevenDelay_ja.md
- manual/SyncSawSynth/SyncSawSynth_en.md
- manual/SyncSawSynth/SyncSawSynth_ja.md
- manual/TrapezoidSynth/TrapezoidSynth_en.md
- manual/TrapezoidSynth/TrapezoidSynth_ja.md
- manual/UltraSynth/UltraSynth_en.md
- manual/UltraSynth/UltraSynth_ja.md
- manual/UltrasonicRingMod/UltrasonicRingMod_en.md
- manual/UltrasonicRingMod/UltrasonicRingMod_ja.md
- manual/WaveCymbal/WaveCymbal_en.md
- manual/WaveCymbal/WaveCymbal_ja.md
- manual/common/contact_installation_guiconfig_en.md
- manual/common/contact_installation_guiconfig_ja.md
- manual/common/gui_barbox_en.md
- manual/common/gui_barbox_ja.md
- manual/common/gui_common_en.md
- manual/common/gui_common_ja.md
- manual/common/gui_knob_en.md
- manual/common/gui_knob_ja.md
- manual/common/gui_xypad_en.md
- manual/common/gui_xypad_ja.md
- manual/common/package_en.md
- manual/common/package_ja.md
- rewrite/README.md
