on: push

env:
  package_path: package

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04  # Ubuntu version can be set here!
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Run script
      run: ci/ci_ubuntu.sh
    - name: Upload
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: vst_ubuntu
        path: vst_ubuntu
